### ISSUE TITLE
Fix error propagation

### ISSUE THREAD

**Issue by redlicha** [openvstorage/gobjfs#7]
Related to #6:

We observe error code `5` (or `-5`, indicating `EIO`) being reported to the client while the actual cause is the absence of the fragment / file. The latter does not necessarily indicate an error from the client's POV  as the requested fragment / file could have been moved away by a maintenance process.
This causes excessive logging.

**Comment by sanjosh** [comment]
@toolslive , need your input on the best way to resolve this issue.  What is the error code you want me to propagate ?

**Comment by toolslive** [comment]
on the client side, we assume that anything that's not 0 indicates an error. I would just pass through the underlying error codes. So, if the file's not present, you return `ENOENT` etc.
